version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buta-baku-app
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
    env_file:
      - .env
    restart: always
