version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buta-baku-app
    ports:
      - "90:80"
    volumes:
      - ./public:/app/public
      - ./log:/app/logs
    env_file:
      - .env
    restart: always
